// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxOhWVj82jE5ryEVFI8TsRAHxs_S7WWVM',
    appId: '1:614544103891:web:eb52dbf38b6185d480f726',
    messagingSenderId: '614544103891',
    projectId: 'exd-evening',
    authDomain: 'exd-evening.firebaseapp.com',
    storageBucket: 'exd-evening.appspot.com',
    measurementId: 'G-YB2TCX117T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFc76K4pdH8wBnCt12YGvsVZmkaCW6yRU',
    appId: '1:614544103891:android:90982520c621c19780f726',
    messagingSenderId: '614544103891',
    projectId: 'exd-evening',
    storageBucket: 'exd-evening.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE5Tq8Q8AVrXu5PDe1jDNYlJ7VLZE3DlE',
    appId: '1:614544103891:ios:2050c9901b30609880f726',
    messagingSenderId: '614544103891',
    projectId: 'exd-evening',
    storageBucket: 'exd-evening.appspot.com',
    iosClientId: '614544103891-baqt1p44gli0i848nri9tqlcdj0d4hsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE5Tq8Q8AVrXu5PDe1jDNYlJ7VLZE3DlE',
    appId: '1:614544103891:ios:2050c9901b30609880f726',
    messagingSenderId: '614544103891',
    projectId: 'exd-evening',
    storageBucket: 'exd-evening.appspot.com',
    iosClientId: '614544103891-baqt1p44gli0i848nri9tqlcdj0d4hsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreApp',
  );
}
